# Generated by Django 6.1 on 2026-08-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose weight'), ('eat_healthier', 'Eat healthier'), ('manage_condition', 'Manage a health condition'), ('gain_muscle', 'Gain muscle'), ('save_money', 'Save money on groceries')], max_length=20)),
                ('household', models.CharField(blank=True, choices=[('solo', 'Just me'), ('couple', 'Couple'), ('family_small', 'Small family (3-4)'), ('family_large', 'Large family (5+)')], max_length=20)),
                ('diet_style', models.CharField(choices=[('no_restrictions', 'No restrictions'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('low_carb', 'Low carb')], default='no_restrictions', max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('cooking_time', models.CharField(blank=True, choices=[('15_20', '15-20 minutes'), ('30_45', '30-45 minutes'), ('45_60', '45-60 minutes'), ('60_plus', '60+ minutes')], max_length=10)),
                ('budget', models.CharField(blank=True, choices=[('budget', 'Budget-friendly'), ('moderate', 'Moderate'), ('flexible', 'Flexible')], max_length=10)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
