# Generated by Django 6.1 on 2026-08-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField()),
                ('weight_kg', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Very active')], max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Lose weight'), ('weight_gain', 'Gain weight'), ('maintenance', 'Maintain weight'), ('muscle_gain', 'Build muscle'), ('general_health', 'General health')], max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('health_conditions', models.JSONField(blank=True, default=list)),
                ('dietary_preference', models.CharField(choices=[('none', 'No restrictions'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('low_sodium', 'Low sodium')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
