# Generated by Django 6.1 on 2026-08-21 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_preset', models.CharField(blank=True, choices=[('nourish', 'Nourish'), ('bloom', 'Bloom'), ('fresh', 'Fresh'), ('heritage', 'Heritage'), ('midnight', 'Midnight')], default='nourish', max_length=20)),
                ('color_mood', models.CharField(choices=[('nourish', 'Nourish (green/cream)'), ('bloom', 'Bloom (pink/cream)'), ('fresh', 'Fresh (teal/white)'), ('heritage', 'Heritage (terracotta/beige)'), ('midnight', 'Midnight (dark green/charcoal)')], default='nourish', max_length=20)),
                ('typography', models.CharField(choices=[('modern', 'Modern'), ('friendly', 'Friendly'), ('elegant', 'Elegant'), ('minimal', 'Minimal')], default='modern', max_length=20)),
                ('card_style', models.CharField(choices=[('sharp', 'Sharp'), ('rounded', 'Rounded'), ('soft', 'Soft')], default='rounded', max_length=20)),
                ('background_style', models.CharField(choices=[('pattern', 'Subtle pattern'), ('warm_pattern', 'Warm pattern'), ('plain', 'Plain'), ('dark', 'Dark')], default='pattern', max_length=20)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('spacious', 'Spacious')], default='comfortable', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('ki', 'Gikuyu'), ('kam', 'Kikamba'), ('ebu', 'Kiembu'), ('mer', 'Kimeru'), ('teso', 'Ateso'), ('luy', 'Luluhya'), ('luo', 'Dholuo')], default='en', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
