# Generated by Django 6.1 on 2026-08-12 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prep_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='GroceryListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('proteins', 'Proteins'), ('vegetables', 'Vegetables'), ('carbs_staples', 'Carbohydrates & Staples'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('other', 'Other')], default='other', max_length=20)),
                ('is_checked', models.BooleanField(default=False)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='mealplans.mealplan')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplans.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mealplans.recipe')),
            ],
            options={
                'ordering': ['day_of_week', 'meal_type'],
                'unique_together': {('meal_plan', 'day_of_week', 'meal_type')},
            },
        ),
    ]
