# Generated by Django 6.1 on 2026-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
