# Generated by Django 6.1 on 2026-08-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_mealplan_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedmeal',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_meals', to='mealplans.recipe'),
        ),
    ]
