# Generated by Django 6.1 on 2026-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0003_alter_plannedmeal_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
