# Generated by Django 6.1 on 2026-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0004_recipe_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbs_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
